[project]
name = "gpt-oss-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "halo>=0.0.31",
    "openai>=1.99.3",
    "openai-harmony>=0.0.3",
]

[dependency-groups]
dev = [
    "ruff>=0.12.8",
]
